name: PostgreSQL
on:
  push:
    paths:
      - .github/workflows/postgresql.yaml
      - postgresql.py
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: nixos:nix
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - run: nix-channel --update
      - run: ./postgresql.py
